name: api_client
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.1.0"
  flutter: 3.3.0

dependencies:
  app_models:
    path: ../app_models
  clock: ^1.1.1
  cloud_firestore: ^3.4.6
  firebase_database: ^9.1.3
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.17.0
  very_good_analysis: ^3.0.1
