name: app_models
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.1.0"
  flutter: 3.3.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.0
  very_good_analysis: ^3.0.1
