include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "*/generated/**"
    - "*/**/intl/**"
    - "*/**/flutter_intl/**"
    - "*/**/*.g.dart"
    - "*/**/*.freezed.dart"
