workflows:
  development:
    name: development
    max_build_duration: 60
    environment:
      flutter: 3.3.0
      xcode: latest
      cocoapods: default
      vars:
        USE_FIREBASE_EMULATOR: false
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - &set_up_key_properties
        name: Set up Android key.properties
        script: |
          echo $FCI_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$FCI_KEYSTORE_PASSWORD
          keyPassword=$FCI_KEY_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF
      - &set_up_local_properties
        name: Set up Android local properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - &setup_keychain
        name: Setup keychain
        script: keychain initialize
      - &fetch_signing_files
        name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "${BUNDLE_ID}" \
              --type IOS_APP_STORE \
              --create
      - &get_packages
        name: Get packages
        script: flutter packages pub get
      - &build_apk
        name: Build Android APK
        script: flutter build apk --release --flavor ${FLAVOR} -t lib/main/main_${FLAVOR}.dart --build-number=$(($PROJECT_BUILD_NUMBER + 300)) --dart-define=STRIPE_KEY=${STRIPE_KEY}
      - &build_aab
        name: Build Android AAB
        script: flutter build appbundle --release --flavor ${FLAVOR} -t lib/main/main_${FLAVOR}.dart --build-number=$(($PROJECT_BUILD_NUMBER + 300)) --dart-define=STRIPE_KEY=${STRIPE_KEY}
      - &setup_signing_certificates
        name: Set up signing certificate
        script: keychain add-certificates
      - &use_profiles
        name: Use Xcode profiles
        script: xcode-project use-profiles
      - &pod_install
        name: Run pod install
        script: find . -name "Podfile" -execdir pod install \;
      - &build_ios
        name: Build and sign iOS
        script: flutter build ipa --release --flavor ${FLAVOR} -t lib/main/main_${FLAVOR}.dart --build-number=$(($PROJECT_BUILD_NUMBER + 300)) --export-options-plist=/Users/builder/export_options.plist --dart-define=STRIPE_KEY=${STRIPE_KEY}
      - &upload_dsym
        name: "Upload dsym artifacts to Firebase Crashlytics"
        script: |
          echo "Find build artifacts"
          dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive $CM_BUILD_DIR/build/ios/xcarchive/Runner.xcarchive -name "*.dSYM.zip" | head -1)
          if [[ -z ${dsymPath} ]]
          then
            echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
          else
            echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
            ls -d -- ios/Pods/*
            $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols -gsp ios/Runner/GoogleService-Info.plist -p ios $dsymPath
          fi

    artifacts:
      - build/app/outputs/apk/${FLAVOR}/release/*.apk
      - build/app/outputs/bundle/${FLAVOR}Release/*.aab
      - build/app/outputs/mapping/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8frlAW+WtUBux3MOgWgIVrHwEfMTmZYN+9Q5LcZHPjigCgYIKoZIzj0DAQehRANCAAR6P0JyFFNAD6vmS0qQIDqwPtSxFSyI51EY8J3O4cMiR7ohrOZbSCM4WrLx0tq6g4WQmYjFyjpM49crMDiTeKmC
        key_id: 68D7DT3B7P
        issuer_id: e1d36718-7200-4ea4-98ac-62d8e1f8b0e4
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: $GOOGLE_PLAY_TRACK
