name: fitts

packages:
  - .
  - packages/**

scripts:
  analyze:flutter:
    name: Run static analysis
    run: melos exec --depends-on=very_good_analysis --flutter "fvm flutter analyze"
  build:runner:
    name: Run build runner
    run: melos exec -c 1 --depends-on=build_runner --flutter "fvm flutter pub get && fvm flutter pub run build_runner build --delete-conflicting-outputs"
    select-package:
      depends-on: json_serializable
  build:assets:
    name: Generate all assets
    run: melos exec -c 1 "fluttergen"
    select-package:
      depends-on: flutter_gen_runner

  generate:flutter:watch:
    name: Build freezed code
    run: melos exec -c 1 --depends-on=build_runner --flutter "fvm flutter pub run build_runner watch --delete-conflicting-outputs"
  flutter:clean:
    name: Clean
    run: melos exec --flutter "fvm flutter clean && fvm flutter pub get"
  flutter:test:
    name: Test
    run: melos exec --dir-exists="test" --flutter "fvm flutter test --coverage"
  flutter:upgrade:
    name: Test
    run: melos exec --flutter "fvm flutter pub upgrade"
  build:translations:
    name: Builds translation dart files
    run: melos exec --depends-on=intl_utils --flutter "fvm flutter pub run intl_utils:generate"
