name: fitts
description: A new Flutter project.
publish_to: none

version: 1.0.0+12

environment:
  sdk: ">=2.12.0 <3.1.0"
  flutter: 3.3.0

dependencies:
  animations: ^2.0.3
  api_client:
    path: packages/api_client
  app_models:
    path: packages/app_models
  app_ui:
    path: packages/app_ui
  authentication_client:
    path: packages/authentication_client
  bloc_test: ^9.0.3
  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  exercises_repository:
    path: packages/exercises_repository
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flow_builder: ^0.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_gen_runner: ^4.1.6
  flutter_localizations:
    sdk: flutter

  flutter_native_splash: ^2.2.10+1
  flutter_svg: ^1.0.0
  form_validators:
    path: packages/form_validators
  formz: ^0.4.1
  miniplayer: ^1.0.1
  mocktail: ^0.3.0
  rxdart: ^0.27.3
  sliver_tools: ^0.2.8
  user_profile_repository:
    path: packages/user_profile_repository
  user_stats_repository:
    path: packages/user_stats_repository
  very_good_analysis: ^3.0.1
  workouts_repository:
    path: packages/workouts_repository

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/onboarding/
    - assets/home/

flutter_gen:
  output: lib/generated/
  line_length: 80
  null_safety: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
