include: package:very_good_analysis/analysis_options.2.3.0.yaml
exclude:
  - "*/generated/**"
  - "*/**/intl/**"
  - "*/**/l10n.dart"
  - "*/**/flutter_intl/**"
  - "*/**/*.g.dart"
  - "*/**/*.freezed.dart"
