name: api_models
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.1.0"
  flutter: 3.0.4

dependencies:
  build_runner: ^2.1.8
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_serializable: ^6.1.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0
