name: authentication_client
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.1.0"
  flutter: 3.0.5

dependencies:
  cloud_firestore: ^3.1.13
  equatable: ^2.0.3
  firebase_auth: ^3.3.0
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.1
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
