// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKf-M8Rf14W2J3fKxu7zcCrjM4XEphoBw',
    appId: '1:218415673107:web:207651145219c4011134e6',
    messagingSenderId: '218415673107',
    projectId: 'fitts-eceb5',
    authDomain: 'fitts-eceb5.firebaseapp.com',
    storageBucket: 'fitts-eceb5.appspot.com',
    measurementId: 'G-0CHTZDX5LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnw3kX3qaNS0yRW3FnU9cfe-ZtawA7h6c',
    appId: '1:218415673107:android:fc963af41de4a1831134e6',
    messagingSenderId: '218415673107',
    projectId: 'fitts-eceb5',
    storageBucket: 'fitts-eceb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjrTQALGU0tOSbTHUryCXteH2stwem0A',
    appId: '1:218415673107:ios:5f99c7f5ff317c451134e6',
    messagingSenderId: '218415673107',
    projectId: 'fitts-eceb5',
    storageBucket: 'fitts-eceb5.appspot.com',
    iosClientId:
        '218415673107-2kc1k322fn0cjmene2d6qadkh8ns0lcv.apps.googleusercontent.com',
    iosBundleId: 'com.kamilsikora.fitts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApjrTQALGU0tOSbTHUryCXteH2stwem0A',
    appId: '1:218415673107:ios:5f99c7f5ff317c451134e6',
    messagingSenderId: '218415673107',
    projectId: 'fitts-eceb5',
    storageBucket: 'fitts-eceb5.appspot.com',
    iosClientId:
        '218415673107-2kc1k322fn0cjmene2d6qadkh8ns0lcv.apps.googleusercontent.com',
    iosBundleId: 'com.kamilsikora.fitts',
  );
}
