name: form_inputs
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  formz: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0
