name: app_ui
description: A new Flutter package project.
version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.1.0"
  flutter: 3.3.0

dependencies:
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_gen_runner: ^4.1.6
  flutter_svg: ^1.0.0
  gap: ^2.0.0
  numberpicker: ^2.1.1
  provider: ^6.0.2

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

include: package:very_good_analysis/analysis_options.yaml

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/Questrial/Questrial-Regular.ttf
          weight: 400
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic

flutter_gen:
  output: lib/src/generated/
  line_length: 80
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    package_parameter_enabled: true
