name: form_validators
description: A new Flutter package project.
version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.1.0"
  flutter: 3.0.4

dependencies:
  flutter:
    sdk: flutter
  formz: ^0.4.1

dev_dependencies:
  test: ^1.20.1
  very_good_analysis: ^2.3.0
